project_id = "ggmotdhxlbwdqfnasltt"

[functions.aigent-ai]
verify_jwt = false

[functions.naka-reit-kb-pull]
verify_jwt = false

[functions.naka-reit-kb-push]
verify_jwt = false

[functions.naka-reit-kb-submit-changes]
verify_jwt = false

[functions.naka-reit-kb-review-changes]
verify_jwt = false

[functions.naka-reit-kb-ingest]
verify_jwt = false
