
project_id = "odzaacarlkmxqrpmggwe"

[functions."learn-ai"]
verify_jwt = true

[functions."mondai-ai"]
verify_jwt = false
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type, x-auth-token, x-kb-token, origin",
  "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS"
}

[functions."connect-linkedin"]
verify_jwt = true
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
}

[functions."oauth-callback-linkedin"]
verify_jwt = true
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
}

[functions."connect-twitter"]
verify_jwt = true
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
}

[functions."oauth-callback-twitter"]
verify_jwt = true
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
}

[functions."connect-discord"]
verify_jwt = true
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
}

[functions."oauth-callback-discord"]
verify_jwt = true
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
}

[functions."connect-telegram"]
verify_jwt = true
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
}

[functions."oauth-callback-telegram"]
verify_jwt = true
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
}

[functions."connect-luma"]
verify_jwt = true
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
}

[functions."oauth-callback-luma"]
verify_jwt = true
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
}
